### ISSUE TITLE
[1sp] Bases de datos de Tapas con datos del 2021

### ISSUE THREAD

**Issue by jmperezra** [IESAM-DAM/avila-en-tapas#80]
## Issue
Se pide crear la base de datos NoSql del listado de tapas con la información del concurso del 2021. Se piden estas tareas:
- [x] Crear la estructura completa de tapas.
- [x] Añadir la información de las tapas del 2021 en Firebase.
- [x] Añadir las imágenes de las tapas 2021 en Firebase.
- [x] Enlazar las imágenes con las tapas (base de datos.
- [x] 14 primeras tapas @JavierManc 
- [x] Restantes ( a partir de la 15 inclusive) @AdrianGarGon 

## Recursos
- Link con la información de las tapas: https://www.avilaturismo.com/wp-content/uploads/2021/06/Folleto-Avila-en-Tapas-2021-22-06-21.pdf

**Comment by AdrianGarGon** [comment]
Done.
